name: Raclette
favicon: null
layout_spectrum: 0.7787209423258901
typography_spectrum: 0.6742602332960814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8855177292134613
  lightness: 0.17263117874972522
  saturation: 0.5811512563377619
  rhythmicContrast: 0.33337907982058823
purpose: []
